### ISSUE TITLE
Donor login

### ISSUE THREAD

**Issue by LianaD26** [ElCabris/blood-bank#17]
## Description:
Donors are unable to log in to their accounts via the donor login portal. Upon entering valid credentials, the system either returns an error or redirects them back to the login page without any notification.

## Expected Behavior:
* Donors should be able to log in using their registered user and password.
* Upon successful login, donors should be redirected to their donor's homepage.
* Proper error messages should be displayed if login fails due to incorrect credentials.

Steps to Reproduce:
* Navigate to the donor login page.
* Enter valid user and password.
* Click the "Login" button.

**Comment by ElCabris** [comment]
donor login and donor bank is not the same?
